### PR TITLE
Add steps of OS X 10.9 and older

### PR DESCRIPTION
**Pull request by shakeelmohamed**

### CODE REVIEW

**Comment by loganknecht** [comment]
I'm probs not going to do that :(

Is there a reason you want documentation for OSX 10.9 and older?

**Comment by shakeelmohamed** [comment]
@loganknecht still using it on my work laptop :)

**Comment by loganknecht** [comment]
@shakeelmohamed  Hrm. I am not sure that this approach will work the same as this requires Docker for Mac, which requires 10.10.3.

With the previous Docker Toolbox my understanding is the volume mounting mechanism wasn't as responsive in updating between the host system and vm.

Otherwise in theory this should work if you spin up a docker machine and pull the image on the docker machine the same way.

I'm assuming you have docker toolbox installed allowing you access to docker-machine.
1. Create a docker machine, if you don't have one already available
2. Load the machine into the env
3. Clone this repository
4. cd to this repository's root directory
5. Run the make command

In theory that should work just the same and should load you into the test environment. If you can provide the output of that I might be able to determine if this isn't a feasible configuration for the older docker environment.

**Comment by shakeelmohamed** [comment]
I actually don't have Docker Toolbox installed an I can use the image just fine with those steps and using make.

**Comment by shakeelmohamed** [comment]
I tried it with Docker for Mac on my other laptop and it's much easier. I'm upgrading my work laptop this week anyways so I don't need this anymore 💯

**Pull request closed without merging**
